### ISSUE TITLE
pip install flask-restx erratic behaviour

### ISSUE THREAD

**Issue by upeguiborja** [python-restx/flask-restx#15]
On a previous project i was developing less than a week ago flask-restx was available through pip, today it seems that the package is no longer on pypi.

### **Code**

```python
pip install flask-restx
```
### **Expected Behavior**
flask-restx package should be installed in my python directory or venv

### **Actual Behavior**
flask-restx package installation fails

### **Error Messages/Stack Trace**
```
ERROR: Could not find a version that satisfies the requirement flask-restx (from versions: none)
ERROR: No matching distribution found for flask-restx
```

### **Environment**
- Python 3.0.1
- Flask 1.1.1
- Flask-RESTX latest
- flask-pymongo
- Win 10 Pro build 1909

**Comment by ziirish** [comment]
Hello,Last week I uploaded a "dummy" package on PyPi.org in order to reserve the project name to be able to generate tokens so we can setup the proper release automation.We are still working "in the background" to have everything setup around the project: a proper communication channel, a proper CI, a proper release process, etc.In short, we will soon publish an official package.Sorry for the inconvenience.

**Comment by jamescrowley321** [comment]
Is there an ETA on when you think we can pull the official package?

**Comment by ziirish** [comment]
Hello,

Yes, we are pretty close to publish our first release. Tests are passing and the release automation is in place.

It should be available by the end of the week. FYI, we'll go with 0.1.0 as the version number.

**Comment by jamescrowley321** [comment]
Awesome, thanks.

**Comment by ziirish** [comment]
We are now live! https://pypi.org/project/flask-restx/
