### ISSUE TITLE
Configuring the base url for an app?

### ISSUE THREAD

**Issue by joesafe** [python-restx/flask-restx#171]
I want to set my API to have a prefix of /api against everything (i.e. docs will be located in api/docs), what is the best method to complish this?  I tried using base_url however this does not work for doc or any routes I create:

```
app = Flask(__name__)
api = Api(app, version='1.0', title='API',
    description='A simple API',
    doc='/docs',
    base_url='/api'
) 
```
Do I need to do /api/* across all namespaces I create?  Can I not set this at an app level?
```
app = Flask(__name__)
api = Api(app, version='1.0', title='API',
    description='A simple API',
    doc='/api/docs'
)
fw = api.namespace('api/firmware', description='Firmware Updates API Docs')
```

**Comment by andreykurilin** [comment]
Try the following code:

```python

import flask
import flask_restx

app = flask.Flask(__name__)
api_bp = flask.Blueprint("api", __name__, url_prefix="/api/")
api = flask_restx.Api(
    api_bp, version='1.0', title='API',
    description='A simple API',
    doc='/docs'
)

fw = api.namespace('firmware', description='Firmware Updates API Docs')

app.register_blueprint(api_bp)
```

**Comment by joesafe** [comment]
> Try the following code:
> 
> ```python
> import flask
> import flask_restx
> 
> app = flask.Flask(__name__)
> api_bp = flask.Blueprint("api", __name__, url_prefix="/api/")
> api = flask_restx.Api(
>     api_bp, version='1.0', title='API',
>     description='A simple API',
>     doc='/docs'
> )
> 
> fw = api.namespace('firmware', description='Firmware Updates API Docs')
> 
> app.register_blueprint(api_bp)
> ```

Yeah, I will be using blueprints to structure the api further - checked more and doesn't appear to be a way to change at top via the Api configuration itself (i.e. using base_url or something similar).

Thanks for the reply!

**Comment by kchennen** [comment]
### Question
Is there anyway to set the api.base_url in the swagger.json to have the same value as the api.base_path?

### Context
I have my API launched on my local pc (mypc), and it's being called locally by the front-end machine on `http://mypc:5000/mysite/api/`.

* The default doc url is good: 
`http://mypc:5000/mysite/api/`

* On the doc, the URL towards the swagger.json is good:
`http://mypc:5000/mysite/api/swagger.json`

* And the *api.base.url* too!

* However, the Base URL is still **/mysite/api**, on both the api doc and in the swagger.json

=> I've tried to modify the api.base_url, but since it's a property, I can't set it's value.

### Issue

1. Is there anyway that I can specify the base_path value that appears in the conf swagger.json?
2. Is there anyway that I can force the export additional parameters defined in the **flask_restx.Api(...., myparam=myvalue)** to also appear in the swagger.json?
