### ISSUE TITLE
Hide fields from response based on some conditions

### ISSUE THREAD

**Issue by hasanul23** [python-restx/flask-restx#266]
Suppose, I have the following Model.
```python
model = api.model('Model', {
    'name': fields.String,
    'address': fields.String,
    'date_updated': fields.DateTime(dt_format='rfc822'),
})
```
For some users, I want to send,
```python
{
'name': 'Mr. abc',
'address': 'x'
}
```
 Also, for some other users, I would like to hide some fields
```python
{
'name': 'Mr. abc',
'last_updated': '2050-12-30'
}
```
@noirbizarre, How is it possible now?

Thanks in advance.

**Comment by jhampson-dbre** [comment]
Let me preface this by saying that I've recently learned of graphQL, and it sounds more suited to what you want to do (selectively return fields). So if you are just getting started, I would recommend taking a look at that first. graphQL is a whole different beast from REST apis though, so if you already have an existing REST api project, that might not be easy to implement.

It's not pretty, but here is what we do for conditional output with Flask-RESTx:

1. Set up 2 or more models (we have 1 base model with shared attributes, and then 2  clones of that with different additional attributes)

```python
job_status_model = ns.model('JobStatusModel', {
    'job_template_id': fields.String(description='The template ID that was used to launch the job', example='2403'),
    'job_id': fields.String(description='The job id', example="234964"),
    "dry_run": DryRun(attribute='job_type', description='Indicates if the job was launched in "check" mode')})

job_timeout_model = ns.clone('JobTimeoutModel', job_status_model, {
    'job_status': fields.String(description='Current state of the job', example='running'),
    'result': fields.String(description='Brief summary of the job result', example='job #234964 is taking longer than 30 seconds, unable to retrieve job results'),
})

job_complete_model = ns.clone('JobCompleteModel', job_status_model, {
    'job_status': fields.String(description='Current state of the job', example='successful'),
    'result': fields.String(description='Brief summary of the job result', example='job #234964 completed successfully'),
    'detail': fields.String(description='Detailed job output string'),
    'detail_lines': fields.List(fields.String(), description='Detailed job output formatted as a list'),
})
```

2. Define your route. For simplicity, we decorate the http method with `@marshall_with` with the `job_ complete_model` model. This works for our usecase, because `job_timeout_model ` is really a subset of `job_ complete_model` . With your example, of having 2 separate sets of fields, maybe you would not want to wrap the method...

```python
@ns.route('/job_launch/<int:job_template_id>')
@ns.param('job_template_id', 'A valid job template ID that has been whitelisted')
class JobLaunch(Resource):

    @marshal_with(job_complete_model, skip_none=True)
    def post(self, job_template_id):
        """
        initiate job
        """
```

3. Build out your response object with the "full" data set. Here's what ours looks like, as an example
```python
            results = {
                "job_template_id": job_template_id,
                "job_status": job_data["status"],
                "job_type": job_data["job_type"],
                "job_id": str(job_id),
                "result": job_result,
                "detail": job_detail,
                "detail_lines": job_detail.split('\n')
            }
```

4. Here is where the magic happens. In our scenario, we set up a condition to marshal the results dictionary with `job_timeout_model `. 

```python
if not job_data['event_processing_finished']:
  results = marshal(results, job_timeout_model)

return results
```

Since we have the http method wrapped with `@marshal_with(job_complete_model, skip_none=True)`, the job_complete_model will always be applied during the `return`. Since we use `skip_none=True`, any fields removed by `marshal(results, job_timeout_model)` are suppressed from the response. 

We also could have not used the `@marshal_with` decorator, and done that with conditional logic instead, but then you lose the auto-swagger documentation generation. But if you have different fields coming back from the same endpoint with the same HTTP code, i'm not sure how you would document that with swagger anyways.

Let me know if anything needs clarifying. Hope that this helps!

**Comment by hasanul23** [comment]
Thanks for your time.
Currently, I am doing this without `@marshal_with` decorator, using 
```python
return marshal(data, model_a if condition else model_b)
```

```python
  order_model_public = ns.model('OrderModelPublic', {
       'id': fields.Integer(),
       'status': fields.String()
  }

  order_model_private = ns.inherit("OrderModelPrivate", {
       "user_id": fields.Integer()
  }
```
with these models, my current approach is:
```python
def get():
   # order has no nullable field
    order = {
       'id' : 'xxx',
       'user_id': 'user123',
       'status': "finished"
   } 
   return marshall(order, order_model_private if order_owner else order_model_public)
```
I cannot use your approach for this scenerio. Can you help me solving by your approach?

**Comment by jhampson-dbre** [comment]
I haven't used `ns.inherit`, only `ns.clone`, so I don't know if that changes anything, but I think the code below would be equivalent

```python
order_model_public = ns.model('OrderModelPublic', {
   'id': fields.Integer(),
   'status': fields.String()
}

order_model_private = ns.inherit("OrderModelPrivate", order_model_public {
   "user_id": fields.Integer()
}
```

```python
@ns.marshal_with(order_model_private, skip_none=True)
def get():
   # order has no nullable field
    order = {
       'id' : 'xxx',
       'user_id': 'user123',
       'status': "finished"
   }
   
   if not order_owner:
       order = marshal(order, order_model_public) # This will remove `user_id` key/value from the order dictionary
   
   return order # marshal_with decorator takes affect. If `user_id` key was removed, it will not be in the response due, to `skip_none=True`. If we don't use `skip_none=True`, it would be re-added to reponse with null/none value.
```

I'm not sure that this has much advantage over your current method, other than `@ns.marshal_with` would auto generate the swagger documentation based on the `order_model_private` model. I think you could document this with your current setup by just adding

```python
@ns.doc(body=order_model_private)
def get():
    ...
```
