### ISSUE TITLE
Pb at jsonify 

### ISSUE THREAD

**Issue by NZ26-06** [python-restx/flask-restx#270]
Hi,

I have successfully (almost, I guess) manage to build a start of api.
Unfortunately when I wrap my function into a class I guess an error message. I cannot find explanation for that.

Works fine:

from flask import Flask, jsonify, request, url_for, abort
from flask import make_response
from tuto import app
from tuto.app import db
from tuto.api import bp
from tuto import models
from tuto.models import Entreprise, Offre, User, Candidate
from flask_restx import Resource, Api, fields

app = Flask(name)

message = {}

![b](https://user-images.githubusercontent.com/71227725/103425190-f6179500-4bb0-11eb-81e4-c080edb5be95.jpg)

When I wrap it as a method of a class:, I have message:
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Candidates.

![a](https://user-images.githubusercontent.com/71227725/103425196-fc0d7600-4bb0-11eb-8384-262c273b10b4.jpg)

Does anyone already experienced it ?
Thanks a lot

**Comment by YUMEYA** [comment]
The definition of `app` at line 10 is not necessary. Usually we initialize `Flask` instance only once.

The reason you got the error is that you used the `route` decorator from `Blueprint` instance at line 15, then as a result,  your class `Candidates` was decorated by `Blueprint.route` decorator. When the URL `/<your_bp_prefix>/candidates` is accessed, Flask app will try to dispatch request to the matching view function and run it. In your case, the class `Candidates` will be called, but it does not return a valid response because your `get` method of the class does not run at all!

To fix this problem, you should decorate your resource class with `Namespace.route` decorator, as per: [Scaling your project](https://flask-restx.readthedocs.io/en/latest/scaling.html)

A full quick example would looks like below:

-  in `api/candidates.py`:

```python
from flask_restx import Namespace, Resource

ns = Namespace("candidates")

@ns.route('/')
class Candidates(Resource):
    def get(self):
        return {'msg': 'OK'}
```

- in `api/__init__.py`:

```python
from flask import Blueprint
from flask_restx import Api
from api.candidates import ns

api_bp = Blueprint("api", __name__)
api = Api(api_bp) # initialize api instance and mount it to api_bp

api.add_namespace(ns) # mount your namespace to api
```

- in `app.py`:
```python
from flask import Flask
from api import api_bp

app = Flask(__name__)
app.register_blueprint(api_bp, url_prefix="/api") # mount api_bp to Flask app instance and set prefix
```

Then you can access `/api/candidates/` and everything should works fine.

**Comment by j5awry** [comment]
Closing thanks to the reply by @YUMEYA. That does present the workflow of namespaces and blueprints for restx. We can improve documentation, and possibly add more tutorials and demos around concepts to help this in the future.
