### ISSUE TITLE
Flask-RESTX breaks our swagger-codegen builds

### ISSUE THREAD

**Issue by cinchent** [python-restx/flask-restx#280]
First off, thanks for forking Flask-RESTPlus.  Much needed continuity for that now-dormant progenitor project...

We're just now getting around to migrating our RESTPlus-based code to RESTX, and were pleased to find that it was pretty much a drop-in replacement.  Good job on backward compatibility.

However, that blissful illusion was shattered when we tried to generate SDKs using `swagger-codegen`.  The root problem is with the Swagger spec JSON file generated by RESTX.  At least as evinced by our use case, there are two significant differences from RESTPlus introduced by RESTX:

1. If a space character is specified in the `name` parameter to `namespace.model()`, because RESTX now does a `urllib.quote()` on that parameter, `swagger-codegen` now mishandles the resulting %20 present in the name.  % is not a valid name identifier, so it would probably be better to replace whitespace sequences with _ or somesuch rather than doing an HTTP quote on it.  We worked around this by just removing the whitespace.

2. The more serious problem is in the change to emit keys of the form `"HTTPStatus.OK"` in the `response` dictionaries for each namespace endpoint instead of the hard-coded status values (e.g., `"200"`, etc.).  This `swagger-codegen` chokes hard on, and it ends up generating SDKs that have `None` results for every endpoint.  Our workaround here was to interpose a filtering script that resolves the symbolic keys back into hard-coded values.

Arguably, these incompatibilities should be fixed on the `swagger-codegen` side, in the `mustache` Python templates there, but that team is basically unresponsive and (shall I say) lacks some core Pythonista competency.  Also, I'm submitting this to you as a bug report and not a PR because your core developers should come to consensus about how to solve these problems from a design standpoint.  Whatever the case, you may want to include some `swagger-codegen` compatibility testing as part of your regression suite.

**Comment by j5awry** [comment]
My 2 cents as a maintainer, and former user of swagger-codegen:

this is a swagger-codegen problem, not a flask-restx problem. The generated swagger files meet OpenAPI2.0/Swagger specs. If swagger-codegen is failing to create models because of inability to parse HTTPStatus.OK, that's definitely a swagger-codegen issue. HTTPStatus.OK enum is much more Pythonic way of working than hardcoding numeric values. I'm against changing flask-restx back to the hardcoded numeric values, and much prefer using the Python builtin.

I agree that swagger-codegen is very Java-centric in its approach to everything. But it may be a good opportunity to jump in and help them out. I don't know how well they take contribs, but with 2.5k open issues and 362 open PRs...well...I feel better about how far behind we are :(

**Comment by cinchent** [comment]
Thank you for your comment.  I surmised that this would be the determination from RESTX.  Any previous bug reports or PRs I've submitted to `swagger-codegen` have been met with radio silence; I guess the sheer volume of their backlog explains it.  I generally view forking as a draconian measure, but given their unresponsiveness, that option could creep onto the table for our team.  For now, our workaround suffices (ugly though it is).
