### ISSUE TITLE
Is there any way to show nested json Schemas using Flask-Pydantic in swagger docs

### ISSUE THREAD

**Issue by kajalsingh05443** [python-restx/flask-restx#367]
**Ask a question**
1. Is there any way to define nested  flask_pydantic  JSON schemas on swagger using flask restx?  # #https://github.com/python-restx/flask-restx/issues/232
2. Is there any other way to reduce use of models, dataclasses and schemas in Flask to make simplified code and reducing the repetition. 
3. To migrate the existing project from flask to FastApi, takes how much time and is there any example to change the whole framework from Flask to FastApi as i am new to this?

**Comment by j5awry** [comment]
1. I think you're in the wrong place to ask these questions. flask-restx does not currently support Pydantic as an interface. there are discussions on adding it, and various users have stated that they've found ways to generate the schema, and make it used by restx models, but it's not a supported solution at this time.

as for nested models, there's generally been a bug in flask-restx for several years (as stated in #232 -- i have history because i first hit that bug in restplus probably 4 years ago). While we've done some work on the restx.api, it's never quite solved nested models

2. In a general way, sure, but a lot f the modeling has to do with input and outputs. So it'll depend greatly on how your API and database are structured. You can use `polymorphism` and `inheritance`, or using a factory setup (https://flask-restx.readthedocs.io/en/latest/marshalling.html#the-api-model-factory)
3. I cannot answer for 3, but if you're already using pydantic, then refactoring routes shouldn't be that bad. I can't make an estimate for you, but a lot of the basics are similar between the frameworks.

I'll leave this open for the moment if anyone else from the community wants to chime in. But I think if you're set on using `pydantic`, then `FastpAPI` is the popular Python framework to use.

**Comment by kajalsingh05443** [comment]
@j5awry Thanks for your reply.
I am planning to migrate from Flask to FastAPI but not sure about it, haven't seen any example to nested json schemas to be shown in swagger docs. That's the reason wanted to confirm about FastAPI whether it's a right option to do so.
