### ISSUE TITLE
Are there new maintainer/contributors?

### ISSUE THREAD

**Issue by safe** [python-restx/flask-restx#503]
I'm aware https://github.com/python-restx/flask-restx/issues/462 exists and specifically the comment noting more maintainers have been added (https://github.com/python-restx/flask-restx/issues/462#issuecomment-1257155158) however is this true?

If so, can the new maintainers (i.e. those with merge access who are active) potentially make themselves known to the flask-restx community?

I'm sure many of us would benefit from knowing there are active maintainers and therefore confirming `flask-restx` is still maintained. If this is no longer maintained, we can move to utilise other frameworks (or another fork of `flask-restx` (which was a fork of `flask-restplus` for the same reason we're experiencing now...)).

There are many useful PRs which have been reviewed by others and not merged (same for issues being answered and not closed).

**Comment by nickezekias** [comment]
We really need an answer to this question.
I've put my use of this repo in prod on hold, still seriously reflecting doing the hard work of updating and maintaining it internally in my org or if maintainers are really going to get this moving.

**Comment by cichockimc** [comment]
bump, there seem to be quite a lot of people willing to help, however there is no feedback. It can end up with a new fork, which is not ideal

**Comment by ziirish** [comment]
As stated several times, I have invited new members and have left instructions on how to make new releases.

If you are interested to become a maintainer or know someone who would be interested then let me know and I can still add new people.
Also, before "leaving" the project, I made sure the CI was properly set up and checked the (contributors) documentation so people only have to focus on code and features.

**Comment by cichockimc** [comment]
thank you @ziirish

**Comment by peter-doggart** [comment]
Hi all, 

Apologies for the delay in responding, I had a fairly lengthy break over the festive period for some R&R after a mad year (start-ups, got to love them!). 

It is my intention to find at least a few hours a week this year to maintain or at least help maintain this project going forwards, because we use it pretty extensively ourselves. Having talked with @ziirish behind the scenes, I think this project still has great potential to continue right here, no need for another fork! And thankfully @ziirish is going to hang around for support too. 

I guess the first order of business is to take stock of what is currently broken / needs urgently fixed (eg #485) and any recently submitted PRs. 

@safe @nickezekias Have you got any high priority items you need/want me to look at urgently? 

And Happy New Year everyone!
Pete

**Comment by peter-doggart** [comment]
@safe Would be great if you could lend a hand going forwards! :)
