### ISSUE TITLE
Flask 3.0.0

### ISSUE THREAD

**Issue by Ced1999** [python-restx/flask-restx#566]
**Ask a question**
Flask was updated to version 3.0.0. This seems to break compatibility with flask-restx completely on my end. Are there plans to make them compatible again in the future?

**Comment by Yoshi325** [comment]
At least one part is being tackled here: https://github.com/python-restx/flask-restx/issues/567

So I'd say there is hope.

**Comment by Ryu-CZ** [comment]
I made a few patches for major issues, but tool the `flask-restx` is using to mock test `flask` compatibility are unfortunately also broken by transition to 3.0. So pull request reviews could take some time. 
This unfortunately can put also block your projects from integration of `flask` 3.0. I put a hotfixes to `restx-monkey` 5.1+ which makes 3.0 `flask` and `flask-restx` compatible again so you can test and resolve your own code base compatibilities issues iwhile `flask-restx` teams does the same. I hope this could save you some time.

**Comment by peter-doggart** [comment]
Just pinning this to keep it at the top. It is our intention to update flask-restx to support Flask 3.0.0+ as soon as possible, but it is currently blocked because, as @Ryu-CZ mentioned, we use `pytest-flask` to mock flask components, and it is also broken by the new Flask version. 

Thankfully, the project is still active so hopefully will be fixed shortly. You can follow the discussion here: https://github.com/pytest-dev/pytest-flask/issues/167

**Comment by peter-doggart** [comment]
@safe I've created a PR for this. Can you just run your eye over it and make sure it's all fine? https://github.com/python-restx/flask-restx/pull/579

**Comment by peter-doggart** [comment]
I have now released flask-restx==1.2.0 which contains restrictions on some version until we can get everything updated (still awaiting pytest-flask updates) so that a default installation isn't broken. 

Anyone who wants to make use of restx-monkey can install `flask-restx==1.1.0` and then patch which will allow flask >=3.0.0 usage.

**Comment by nachitox** [comment]
`pytest-flask` was upgraded yesterday.

**Comment by peter-doggart** [comment]
@nachitox Great news. I will try and get everything merged over the coming days, pretty flat out with other things this week.

**Comment by diogper** [comment]
Great news!

**Comment by peter-doggart** [comment]
Flask-restx community, thanks for your patience on this! :) 

I have just merged all the most recent PRs and done some general tidy up. Flask-restx 1.3.0 should hit PyPi in a few minutes. Flask and Werkzeug >=3.0.0 should now work correctly again.

There is still a deprecation warning relating to jsonschema, however it doesn't currently impact functionality. I will hopefully get some time to deep dive on how to fix it over the coming weeks. 

Please file a new issue (or PR if you have the time!) if you find anything is broken or funny.

**Comment by martin-thoma** [comment]
The new version is on PyPI. Should this be closed?

**Comment by gdeleon23** [comment]
Hi :)
Sorry but error still present with new versions:

```
> pytest tests_integration

ImportError while loading conftest '/code/tests_integration/conftest.py'.
tests_integration/conftest.py:11: in <module>
    from app import app
....
    from flask_restx import Api
../../.local/lib/python3.10/site-packages/flask_restx/__init__.py:5: in <module>
    from .api import Api  # noqa
../../.local/lib/python3.10/site-packages/flask_restx/api.py:23: in <module>
    from flask.scaffold import _endpoint_from_view_func
E   ModuleNotFoundError: No module named 'flask.scaffold'
```

```
> pip3 freeze | grep -iE 'flask|werk'
Flask==3.0.2
Flask-Cors==4.0.0
Flask-JWT-Extended==4.6.0
flask-restx==1.3.0
Flask-SQLAlchemy==3.1.1
Flask-WTF==1.2.1
pytest-flask==1.3.0
Werkzeug==3.0.1
```
