### ISSUE TITLE
How to configure package namespaces?

### ISSUE THREAD

**Issue by Quidge** [python-restx/flask-restx#7]
The [documentation only shows](https://flask-restx.readthedocs.io/en/latest/scaling.html) an example where all related `Dog` functionality is inside a `dog.py` module with the `api = Namespace('dogs', description='Dogs related operations')` declaration at the top.

But what if I wish to have multiple an entire pacakge devoted to a namespace? I was expecting to be able to do it like this:

```
project
├-- app.py
├-- dog_api
    ├-- __init__.py  <---- `api = Namespace('dogs', path='/dogs')`
    ├-- sounds.py <------ `from . import api; @api.route('/sounds/<int:soundid>`
    ├-- foods.py <------ `from . import api; @api.route('/foods/<int:foodid>``
    ├-- breeds.py <------ `from . import api; @api.route('/breeds/<int:breedid>``
```

The code for app.py would have this:

```python
from .dog_api import api as dog_api


api = Api(app)
api.add_namespace(dog_api, path='/dogs')
```

Obviously this is example code, but I have a real project set up very similarly to this and it's running into route errors. When running tests it's apparent that the routes aren't being registered in time/properly and trying to access `/dogs/sounds/something` will cause a 404. I believe it has to do with the order that I'm importing/`add_namespace`ing.

What should the proper import order/order to use `add_namespace` be when a namespace represents an entire pacakge?

**Comment by Quidge** [comment]
With the same setup as above, I was able to get it working with a `dog_api/__init__.py` file that looks like this:

```python
api = Namespace('dog_api')

# These routes must be imported here below the `api` definition to be seen by any calls to `.add_namespace(api)`
from . import sounds, foods, breeds
```

I'm worried that this will get me into confusing circular import issues in the future, but this does work.

I adapted [this page on the Flask docs](https://flask.palletsprojects.com/en/1.1.x/patterns/packages/#larger-applications) to get to this step.

Still very interested in what the 'canonical' way to do this would be from someone who has used RESTplus/x a lot, but otherwise this can be closed.

**Comment by SteadBytes** [comment]
Hello @Quidge , thanks for using the project. You are correct that those routes won't be added to the Flask application because they are not imported - as such the code in those files will never get run. As stated in the Flask docs you posted, the circular import here is "ok" as long as those objects aren't actually being used in `dog_api/__init__.py`. One way to avoid this would be to make each of these files it's own namespaces or use multiple blueprints as shown in the docs here https://flask-restx.readthedocs.io/en/latest/scaling.html#multiple-namespaces . 

Since this isn't an issue/bug I'm going to close this, but please head on over to the Gitter channel if you would like more help! :smile:
